/* React router */
export const REACT_ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

/* Main layout */
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_CHANGED = 'MAIN_LAYOUT_SERVER_VIEW_WIDTH_CHANGED'
export const MAIN_LAYOUT_SERVER_VIEW_REQUEST_WIDTH_RESTORE = 'MAIN_LAYOUT_SERVER_VIEW_REQUEST_WIDTH_RESTORE'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORE_REQUESTED = 'MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORE_REQUESTED'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORED = 'MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORED'

/* Server view */
export const SERVER_VIEW_REQUEST_SERVER_LIST = 'SERVER_VIEW_REQUEST_SERVER_LIST'
export const SERVER_VIEW_SERVER_LIST_REQUESTED = 'SERVER_VIEW_SERVER_LIST_REQUESTED'
export const SERVER_VIEW_SERVER_LIST_CHANGED = 'SERVER_VIEW_SERVER_LIST_CHANGED'
export const SERVER_VIEW_REQUEST_ADD_SERVER = 'SERVER_VIEW_REQUEST_ADD_SERVER'
export const SERVER_VIEW_ADD_SERVER = 'SERVER_VIEW_ADD_SERVER'
export const SERVER_VIEW_SERVER_SELECTED = 'SERVER_VIEW_SERVER_SELECTED'
export const SERVER_LIST_REQUEST_UPDATE_SERVER = 'SERVER_LIST_REQUEST_UPDATE_SERVER'
export const SERVER_VIEW_UPDATE_SERVER = 'SERVER_VIEW_UPDATE_SERVER'
export const SERVER_VIEW_SERVER_CHANGED = 'SERVER_VIEW_SERVER_UPDATED'
