/* Main layout */
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_CHANGED = 'main-layout/SERVER_VIEW_WIDTH_CHANGED'
export const MAIN_LAYOUT_SERVER_VIEW_REQUEST_WIDTH_RESTORE = 'main-layout/SERVER_VIEW_REQUEST_WIDTH_RESTORE'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORE_REQUESTED = 'main-layout/SERVER_VIEW_WIDTH_RESTORE_REQUESTED'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORED = 'main-layout/SERVER_VIEW_WIDTH_RESTORED'

/* Server */
export const SERVER_SERVER_SAVED = 'server/SERVER_SAVED'
export const SERVER_SERVER_REMOVED = 'server/SERVER_REMOVED'

/* Server view */
export const SERVER_REQUEST_SERVER_LIST = 'server/REQUEST_SERVER_LIST'
export const SERVER_SERVER_LIST_REQUESTED = 'server/SERVER_LIST_REQUESTED'
export const SERVER_SERVER_LIST_CHANGED = 'server/SERVER_LIST_CHANGED'

/* Server list */
export const SERVER_SERVER_SELECTED = 'server/SERVER_SELECTED'
export const SERVER_KEY_SELECTED = 'server/KEY_SELECTED'
export const SERVER_TOGGLE_SERVER_LIST_ITEM_EXPAND = 'server/TOGGLE_SERVER_LIST_ITEM_EXPAND'
export const SERVER_OPEN_KEY = 'server/OPEN_KEY'
export const SERVER_REQUEST_KEYS = 'server/REQUEST_KEYS'
export const SERVER_KEYS_LOADED = 'server/KEYS_LOADED'
export const SERVER_KEYS_LOAD_FAILED = 'server/SERVER_KEYS_LOAD_FAILED'

/* Server toolbox */
export const SERVER_EDIT_SERVER = 'server/EDIT_SERVER'
export const SERVER_REMOVE_SERVER = 'server/REMOVE_SERVER'
export const SERVER_FILTER_CHANGED = 'server/FILTER_CHANGED'

/* Server settings */
export const SERVER_REQUEST_CONNECTION_TEST = 'server/REQUEST_CONNECTION_TEST'
export const SERVER_SET_SERVER = 'server/SET_SERVER'

/* Key view */
export const KEY_REQUEST_DATA = 'key/REQUEST_DATA'
export const KEY_DATA_RECEIVED = 'key/DATA_RECEIVED'
export const KEY_DATA_REQUEST_FAILED = 'key/DATA_REQUEST_FAILED'

export const KEY_SUBSCRIBE = 'key/SUBSCRIBE'
export const KEY_SUBSCRIBED = 'key/SUBSCRIBED'
export const KEY_SUBSCRIPTION_FAILED = 'key/SUBSCRIPTION_FAILED'

export const KEY_UNSUBSCRIBE = 'key/UNSUBSCRIBE'
export const KEY_UNSUBSCRIBED = 'key/UNSUBSCRIBE'
export const KEY_UNSUBSCRIPTION_FAILED = 'key/UNSUBSCRIBE'
