/*Tree view on main layout*/
export const TREE_VIEW_WIDTH_CHANGED = "TREE_VIEW_WIDTH_CHANGED";
export const TREE_VIEW_WIDTH_RESTORE_REQUESTED = "TREE_VIEW_WIDTH_RESTORE_REQUESTED";
export const TREE_VIEW_WIDTH_RESTORED = "TREE_VIEW_WIDTH_RESTORED";
