export const REQUEST_DATA = 'key/REQUEST_DATA'
export const DATA_RECEIVED = 'key/DATA_RECEIVED'
export const DATA_REQUEST_FAILED = 'key/DATA_REQUEST_FAILED'

export const SUBSCRIBE = 'key/SUBSCRIBE'
export const SUBSCRIBED = 'key/SUBSCRIBED'
export const SUBSCRIPTION_FAILED = 'key/SUBSCRIPTION_FAILED'

export const UNSUBSCRIBE = 'key/UNSUBSCRIBE'
export const UNSUBSCRIBED = 'key/UNSUBSCRIBED'
export const UNSUBSCRIPTION_FAILED = 'key/UNSUBSCRIPTION_FAILED'

export default {
  REQUEST_DATA,
  DATA_RECEIVED,
  DATA_REQUEST_FAILED,

  SUBSCRIBE,
  SUBSCRIBED,
  SUBSCRIPTION_FAILED,

  UNSUBSCRIBE,
  UNSUBSCRIBED,
  UNSUBSCRIPTION_FAILED
}
