export const KEY_REQUEST_DATA = 'key/REQUEST_DATA'
export const KEY_DATA_RECEIVED = 'key/DATA_RECEIVED'
export const KEY_DATA_REQUEST_FAILED = 'key/DATA_REQUEST_FAILED'

export const KEY_SUBSCRIBE = 'key/SUBSCRIBE'
export const KEY_SUBSCRIBED = 'key/SUBSCRIBED'
export const KEY_SUBSCRIPTION_FAILED = 'key/SUBSCRIPTION_FAILED'

export const KEY_UNSUBSCRIBE = 'key/UNSUBSCRIBE'
export const KEY_UNSUBSCRIBED = 'key/UNSUBSCRIBED'
export const KEY_UNSUBSCRIPTION_FAILED = 'key/UNSUBSCRIPTION_FAILED'

export default {
  KEY_REQUEST_DATA,
  KEY_DATA_RECEIVED,
  KEY_DATA_REQUEST_FAILED,

  KEY_SUBSCRIBE,
  KEY_SUBSCRIBED,
  KEY_SUBSCRIPTION_FAILED,

  KEY_UNSUBSCRIBE,
  KEY_UNSUBSCRIBED,
  KEY_UNSUBSCRIPTION_FAILED
}
