// @flow

export const SERVER_KEY_TREE_WIDTH_CHANGED = 'mainLayout/SERVER_KEY_TREE_WIDTH_CHANGED'

export const SERVER_KEY_TREE_REQUEST_WIDTH_RESTORE = 'mainLayout/SERVER_KEY_TREE_REQUEST_WIDTH_RESTORE'
export const SERVER_KEY_TREE_WIDTH_RESTORE_REQUESTED = 'mainLayout/SERVER_KEY_TREE_WIDTH_RESTORE_REQUESTED'
export const SERVER_KEY_TREE_WIDTH_RESTORED = 'mainLayout/SERVER_KEY_TREE_WIDTH_RESTORED'

export default {
  SERVER_KEY_TREE_WIDTH_CHANGED,

  SERVER_KEY_TREE_REQUEST_WIDTH_RESTORE,
  SERVER_KEY_TREE_WIDTH_RESTORE_REQUESTED,
  SERVER_KEY_TREE_WIDTH_RESTORED
}
