export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_CHANGED = 'main-layout/SERVER_VIEW_WIDTH_CHANGED'
export const MAIN_LAYOUT_SERVER_VIEW_REQUEST_WIDTH_RESTORE = 'main-layout/SERVER_VIEW_REQUEST_WIDTH_RESTORE'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORE_REQUESTED = 'main-layout/SERVER_VIEW_WIDTH_RESTORE_REQUESTED'
export const MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORED = 'main-layout/SERVER_VIEW_WIDTH_RESTORED'

export default {
  MAIN_LAYOUT_SERVER_VIEW_REQUEST_WIDTH_RESTORE,
  MAIN_LAYOUT_SERVER_VIEW_WIDTH_CHANGED,
  MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORE_REQUESTED,
  MAIN_LAYOUT_SERVER_VIEW_WIDTH_RESTORED
}
