export const SERVER_REQUEST_CONNECTION_TEST = 'server/REQUEST_CONNECTION_TEST'
export const SERVER_SET_SERVER = 'server/SET_SERVER'

export default {
  SERVER_REQUEST_CONNECTION_TEST,
  SERVER_SET_SERVER
}
