export const SERVER_SERVER_SELECTED = 'server/SERVER_SELECTED'
export const SERVER_KEY_SELECTED = 'server/KEY_SELECTED'
export const SERVER_TOGGLE_SERVER_LIST_ITEM_EXPAND = 'server/TOGGLE_SERVER_LIST_ITEM_EXPAND'
export const SERVER_OPEN_KEY = 'server/OPEN_KEY'
export const SERVER_REQUEST_KEYS = 'server/REQUEST_KEYS'
export const SERVER_KEYS_LOADED = 'server/KEYS_LOADED'
export const SERVER_KEYS_LOAD_FAILED = 'server/SERVER_KEYS_LOAD_FAILED'

export default {
  SERVER_SERVER_SELECTED,
  SERVER_KEY_SELECTED,
  SERVER_TOGGLE_SERVER_LIST_ITEM_EXPAND,
  SERVER_OPEN_KEY,
  SERVER_REQUEST_KEYS,
  SERVER_KEYS_LOADED,
  SERVER_KEYS_LOAD_FAILED
}