export const SERVER_REQUEST_SERVER_LIST = 'server/REQUEST_SERVER_LIST'
export const SERVER_SERVER_LIST_REQUESTED = 'server/SERVER_LIST_REQUESTED'
export const SERVER_SERVER_LIST_CHANGED = 'server/SERVER_LIST_CHANGED'

export default {
  SERVER_REQUEST_SERVER_LIST,
  SERVER_SERVER_LIST_REQUESTED,
  SERVER_SERVER_LIST_CHANGED
}
